name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'corretto'
          java-version: 25
          cache: 'gradle'

      - name: Build Plugin
        run: ./gradlew buildPlugin

      # https://github.com/actions/upload-artifact/issues/702
      - name: Unzip the plugin
        id: plugin_name
        run: |
          BASENAME=$(basename $(ls build/distributions/*.zip | head -n 1) .zip)
          unzip build/distributions/*.zip -d $BASENAME
          echo "basename=$BASENAME" >> $GITHUB_OUTPUT

      - name: Upload plugin ZIP directly
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.plugin_name.outputs.basename }}
          path: ${{ steps.plugin_name.outputs.basename }}
